name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.5'

      - name: Flutter pub get
        run: flutter pub get

      - name: Run golden tests
        run: flutter test --tags=golden
      - name: Upload golden diffs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-failures
          path: test/**/failures/**
          if-no-files-found: ignore


      - name: Enable web
        run: flutter config --enable-web

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Start ChromeDriver
        run: |
          chromedriver --version
          chromedriver --port=4444 &
          sleep 2

      - name: Run integration (web) and take screenshots
        env:
          CHROME_EXECUTABLE: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/app_flow_test.dart \
            -d web-server \
            --browser-name=chrome

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/**/*.png
          if-no-files-found: warn

